M48
; DRILL file {KiCad 9.0.6} date 2025-11-16T15:46:10-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-16T15:46:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1417
%
G90
G05
T1
X2.6Y-1.92
X2.61Y-4.9
X7.4Y-4.9
X7.41Y-1.92
T2
X6.91Y-1.5
X6.91Y-5.33
M30
